<!doctype html>
<html lang="en" class="scheme-light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>RDS Monitoring · {{ config('app.name', 'Monitoring Agent') }}</title><script>if(localStorage.getItem('monitoring-agent-theme')==='dark'){document.documentElement.classList.add('dark')}</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100"><x-app-header active="cloud" />
<main class="mx-auto max-w-screen-2xl px-4 py-6 sm:px-6"><div id="cloud-database-dashboard" data-endpoint="{{ route('cloud.databases.data') }}">
    <div><p class="text-sm font-medium text-emerald-600">AWS / RDS</p><h1 class="text-2xl font-semibold">Database Monitoring</h1><p class="mt-1 text-sm text-slate-500">Per-database CloudWatch health, I/O latency, capacity, connections, and Performance Insights SQL load.</p></div>
    @if($databases->isEmpty())<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-10 text-center dark:border-slate-800 dark:bg-slate-900"><h2 class="text-xl font-semibold">No RDS databases available</h2><p class="mt-2 text-sm text-slate-500">Wait for cloud synchronization or verify that the role permits RDS discovery.</p></section>@else
    <div class="mt-5 flex flex-wrap items-end justify-between gap-4"><div class="flex flex-wrap gap-3"><label class="text-xs text-slate-400">Database<select id="cloud-database-select" class="mt-1 block min-w-72 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900">@foreach($databases as $database)<option value="{{ $database->id }}">{{ $database->name }} · {{ $database->metadata['engine'] ?? 'RDS' }}</option>@endforeach</select></label><label class="text-xs text-slate-400">Time range<select id="cloud-database-range" class="mt-1 block rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="1">Last hour</option><option value="6">Last 6 hours</option><option value="24">Last 24 hours</option><option value="72">Last 3 days</option><option value="168">Last 7 days</option></select></label></div><div class="flex items-center gap-2 pb-2 text-xs text-slate-400"><span id="cloud-database-dot" class="size-2 rounded-full bg-slate-500"></span><span id="cloud-database-status">Loading telemetry…</span></div></div>
    <div id="cloud-database-no-data" class="mt-5 hidden rounded-xl border border-slate-200 bg-white p-8 text-center dark:border-slate-800 dark:bg-slate-900"><h2 class="text-lg font-semibold">No RDS metrics found</h2><p class="mt-2 text-sm text-slate-500">This database has no CloudWatch samples in the selected range.</p></div>
    <div id="cloud-database-telemetry" class="hidden">
        <nav data-cloud-detail-tabs class="mt-5 flex gap-1 border-b border-slate-200 dark:border-slate-800" aria-label="RDS monitoring sections"><button type="button" data-cloud-detail-tab="overview" class="border-b-2 border-emerald-500 px-4 py-3 text-sm font-medium text-emerald-700 dark:text-emerald-300">Overview</button><button type="button" data-cloud-detail-tab="insights" class="border-b-2 border-transparent px-4 py-3 text-sm text-slate-500">Query insights</button><button type="button" data-cloud-detail-tab="configuration" class="border-b-2 border-transparent px-4 py-3 text-sm text-slate-500">Configuration</button></nav>
        <div data-cloud-detail-panel="overview">
        <div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><section class="metric-card"><p>CPU now</p><strong id="rds-cpu">—</strong><span id="rds-cpu-peak">Peak —</span></section><section class="metric-card"><p>Connections</p><strong id="rds-connections">—</strong><span>Current clients</span></section><section class="metric-card"><p>Free memory</p><strong id="rds-memory">—</strong><span>Available to engine</span></section><section class="metric-card"><p>Free storage</p><strong id="rds-storage">—</strong><span id="rds-storage-percent">of provisioned</span></section><section class="metric-card"><p>I/O latency</p><strong id="rds-latency">—</strong><span>Read / write</span></section></div>
        <div class="mt-4 grid gap-4 xl:grid-cols-2"><section class="chart-panel"><div class="panel-heading"><h2>CPU utilization</h2><span>Percent</span></div><div class="h-64"><canvas id="rds-cpu-chart" class="block size-full"></canvas></div></section><section class="chart-panel"><div class="panel-heading"><h2>Database connections</h2><span>Count</span></div><div class="h-64"><canvas id="rds-connections-chart" class="block size-full"></canvas></div></section><section class="chart-panel"><div class="panel-heading"><h2>Read and write latency</h2><span>Milliseconds</span></div><div class="h-64"><canvas id="rds-latency-chart" class="block size-full"></canvas></div></section><section class="chart-panel"><div class="panel-heading"><h2>Read and write IOPS</h2><span>Operations / second</span></div><div class="h-64"><canvas id="rds-iops-chart" class="block size-full"></canvas></div></section></div>
        </div>
        <section data-cloud-detail-panel="insights" class="chart-panel mt-5 hidden overflow-hidden"><div class="panel-heading"><h2>Top SQL by database load</h2><span id="rds-query-window">Performance Insights</span></div><div class="overflow-x-auto"><table class="min-w-[900px] w-full text-left text-sm"><thead class="text-xs text-slate-500"><tr><th class="py-2">SQL digest</th><th class="text-right">DB load</th><th class="text-right">Avg execution</th><th class="text-right">Calls / sec</th></tr></thead><tbody id="rds-query-table" class="divide-y divide-slate-200 dark:divide-slate-800"></tbody></table></div><p class="mt-3 text-xs text-slate-500">DB load is average active sessions. Execution latency and call rate appear only when the database engine exposes compatible per-SQL Performance Insights counters.</p></section>
        <section data-cloud-detail-panel="configuration" class="chart-panel mt-5 hidden"><div class="panel-heading"><h2>Database configuration</h2><span id="rds-resource-id">—</span></div><dl class="grid gap-4 text-sm sm:grid-cols-2 xl:grid-cols-6"><div><dt class="text-xs text-slate-500">Engine</dt><dd id="rds-engine" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">Class</dt><dd id="rds-class" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">Region / zone</dt><dd id="rds-region" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">Storage</dt><dd id="rds-provisioned" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">High availability</dt><dd id="rds-multi-az" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">Endpoint</dt><dd id="rds-endpoint" class="mt-1 truncate font-mono text-xs">—</dd></div></dl></section>
    </div><p id="cloud-database-error" class="mt-4 hidden rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-500"></p>@endif
</div></main></body></html>
