<!doctype html>
<html lang="en" class="scheme-light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>AWS Cloud · {{ config('app.name', 'Monitoring Agent') }}</title><script>if(localStorage.getItem('monitoring-agent-theme')==='dark'){document.documentElement.classList.add('dark')}</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100"><x-app-header active="cloud" />
<main class="mx-auto max-w-screen-2xl px-4 py-6 sm:px-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-medium text-emerald-600">Cloud inventory</p><h1 class="text-2xl font-semibold">AWS Cloud</h1><p class="mt-1 text-sm text-slate-500">Account and resource totals. Open a resource for individual telemetry.</p></div><div class="flex gap-2"><a href="{{ route('cloud.recommendations') }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium dark:border-slate-700 dark:bg-slate-900">Recommendations @if(($summary['findings'] ?? 0) > 0)<span class="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-xs text-amber-700 dark:bg-amber-950 dark:text-amber-300">{{ $summary['findings'] }}</span>@endif</a>@if(auth()->user()->is_admin)<a href="{{ route('settings.index') }}#cloud" class="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium dark:border-slate-700 dark:bg-slate-900">Cloud settings</a>@endif</div></div>
    @if($connections->isEmpty())
        <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-10 text-center dark:border-slate-800 dark:bg-slate-900"><h2 class="text-xl font-semibold">No AWS account connected</h2><p class="mt-2 text-sm text-slate-500">Create the read-only role and add its ARN under Cloud settings.</p>@if(auth()->user()->is_admin)<a href="{{ route('settings.index') }}#cloud" class="mt-5 inline-block rounded-xl bg-emerald-500 px-5 py-3 font-medium text-white">Connect AWS</a>@endif</section>
    @else
        <div class="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-7">
            <section class="metric-card"><p>AWS accounts</p><strong>{{ $summary['accounts'] }}</strong><span>Connected roles</span></section>
            <section class="metric-card"><p>All resources</p><strong>{{ $summary['resources'] }}</strong><span>Discovered inventory</span></section>
            <section class="metric-card"><p>EC2 instances</p><strong>{{ $summary['instances'] }}</strong><span>All states</span></section>
            <section class="metric-card"><p>RDS databases</p><strong>{{ $summary['databases'] }}</strong><span>DB instances</span></section>
            <section class="metric-card"><p>Running</p><strong>{{ $summary['running'] }}</strong><span>EC2 instances</span></section>
            <section class="metric-card"><p>Stopped</p><strong>{{ $summary['stopped'] }}</strong><span>EC2 instances</span></section>
            <section class="metric-card"><p>Regions</p><strong>{{ $summary['regions'] }}</strong><span>With resources</span></section>
        </div>
        <section class="chart-panel mt-5 overflow-hidden"><div class="panel-heading"><h2>EC2 instances</h2><a href="{{ route('cloud.instances') }}" class="text-emerald-600">Open instance monitoring →</a></div><div class="overflow-x-auto"><table class="min-w-[800px] w-full text-left text-sm"><thead class="text-xs text-slate-500"><tr><th class="py-2">Instance</th><th>Account</th><th>Region / zone</th><th>Type</th><th>Private IP</th><th>Status</th><th></th></tr></thead><tbody class="divide-y divide-slate-200 dark:divide-slate-800">@forelse($resources->where('service','ec2')->where('type','instance') as $resource)<tr><td class="py-3"><p class="font-medium">{{ $resource->name }}</p><p class="font-mono text-xs text-slate-500">{{ $resource->resource_id }}</p></td><td>{{ $resource->connection->name }}</td><td>{{ $resource->region }}<p class="text-xs text-slate-500">{{ $resource->availability_zone }}</p></td><td>{{ $resource->instance_type }}</td><td class="font-mono text-xs">{{ $resource->metadata['private_ip'] ?? '—' }}</td><td><span class="inline-flex rounded-full px-2 py-1 text-xs {{ $resource->state === 'running' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' }}">{{ $resource->state ?? 'unknown' }}</span></td><td><a href="{{ route('cloud.instances', ['resource_id' => $resource->id]) }}" class="font-medium text-emerald-600">Monitor</a></td></tr>@empty<tr><td colspan="7" class="py-8 text-center text-slate-500">No EC2 instances have been synchronized yet.</td></tr>@endforelse</tbody></table></div></section>
        <section class="chart-panel mt-5 overflow-hidden"><div class="panel-heading"><h2>RDS databases</h2><a href="{{ route('cloud.databases') }}" class="text-emerald-600">Open database monitoring →</a></div><div class="overflow-x-auto"><table class="min-w-[760px] w-full text-left text-sm"><thead class="text-xs text-slate-500"><tr><th class="py-2">Database</th><th>Engine</th><th>Class</th><th>Region / zone</th><th>Storage</th><th>Status</th><th></th></tr></thead><tbody class="divide-y divide-slate-200 dark:divide-slate-800">@forelse($resources->where('service','rds')->where('type','db-instance') as $resource)<tr><td class="py-3 font-medium">{{ $resource->name }}</td><td>{{ $resource->metadata['engine'] ?? '—' }} {{ $resource->metadata['engine_version'] ?? '' }}</td><td>{{ $resource->instance_type }}</td><td>{{ $resource->region }}<p class="text-xs text-slate-500">{{ $resource->availability_zone }}</p></td><td>{{ $resource->metadata['allocated_storage_gib'] ?? '—' }} GiB</td><td><span class="inline-flex rounded-full px-2 py-1 text-xs {{ $resource->state === 'available' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300' }}">{{ $resource->state ?? 'unknown' }}</span></td><td><a href="{{ route('cloud.databases', ['resource_id' => $resource->id]) }}" class="font-medium text-emerald-600">Monitor</a></td></tr>@empty<tr><td colspan="7" class="py-8 text-center text-slate-500">No RDS databases have been synchronized yet.</td></tr>@endforelse</tbody></table></div></section>
    @endif
</main></body></html>
