<!doctype html>
<html lang="en" class="scheme-light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>EC2 Monitoring · {{ config('app.name', 'Monitoring Agent') }}</title><script>if(localStorage.getItem('monitoring-agent-theme')==='dark'){document.documentElement.classList.add('dark')}</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100"><x-app-header active="cloud" />
<main class="mx-auto max-w-screen-2xl px-4 py-6 sm:px-6"><div id="cloud-instance-dashboard" data-endpoint="{{ route('cloud.instances.data') }}">
    <div><p class="text-sm font-medium text-emerald-600">AWS / EC2</p><h1 class="text-2xl font-semibold">Instance Monitoring</h1><p class="mt-1 text-sm text-slate-500">Per-instance CloudWatch telemetry using the same time-series layout as server monitoring.</p></div>
    @if($instances->isEmpty())<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-10 text-center dark:border-slate-800 dark:bg-slate-900"><h2 class="text-xl font-semibold">No EC2 instances available</h2><p class="mt-2 text-sm text-slate-500">Wait for the first cloud synchronization or review the AWS connection.</p></section>@else
    <div class="mt-5 flex flex-wrap items-end justify-between gap-4"><div class="flex flex-wrap gap-3"><label class="text-xs text-slate-400">Instance<select id="cloud-resource-select" class="mt-1 block min-w-72 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900">@foreach($instances as $instance)<option value="{{ $instance->id }}">{{ $instance->name }} · {{ $instance->resource_id }}</option>@endforeach</select></label><label class="text-xs text-slate-400">Time range<select id="cloud-range-select" class="mt-1 block rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="1">Last hour</option><option value="6">Last 6 hours</option><option value="24">Last 24 hours</option><option value="72">Last 3 days</option><option value="168">Last 7 days</option></select></label></div><div class="flex items-center gap-2 pb-2 text-xs text-slate-400"><span id="cloud-status-dot" class="size-2 rounded-full bg-slate-500"></span><span id="cloud-status">Loading telemetry…</span></div></div>
    <div id="cloud-no-data" class="mt-5 hidden rounded-xl border border-slate-200 bg-white p-8 text-center dark:border-slate-800 dark:bg-slate-900"><h2 class="text-lg font-semibold">No CloudWatch data found</h2><p class="mt-2 text-sm text-slate-500">This instance has no samples in the selected range. Newly connected accounts may take one polling interval to appear.</p></div>
    <div id="cloud-telemetry" class="hidden">
        <nav data-cloud-detail-tabs class="mt-5 flex gap-1 border-b border-slate-200 dark:border-slate-800" aria-label="EC2 monitoring sections"><button type="button" data-cloud-detail-tab="overview" class="border-b-2 border-emerald-500 px-4 py-3 text-sm font-medium text-emerald-700 dark:text-emerald-300">Overview</button><button type="button" data-cloud-detail-tab="insights" class="border-b-2 border-transparent px-4 py-3 text-sm text-slate-500">Storage insights</button><button type="button" data-cloud-detail-tab="configuration" class="border-b-2 border-transparent px-4 py-3 text-sm text-slate-500">Configuration</button></nav>
        <div data-cloud-detail-panel="overview">
        <div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><section class="metric-card"><p>CPU now</p><strong id="cloud-cpu-now">—</strong><span id="cloud-cpu-peak">Peak —</span></section><section class="metric-card"><p>OS memory used</p><strong id="cloud-memory-used">—</strong><span>CloudWatch Agent</span></section><section class="metric-card"><p>Network in</p><strong id="cloud-network-in">—</strong><span>Latest interval</span></section><section class="metric-card"><p>Network out</p><strong id="cloud-network-out">—</strong><span>Latest interval</span></section><section class="metric-card"><p>Instance status</p><strong id="cloud-instance-state">—</strong><span id="cloud-last-sample">Last sample —</span></section></div>
        <div class="mt-4 grid gap-4 xl:grid-cols-2"><section class="chart-panel"><div class="panel-heading"><h2>CPU utilization</h2><span>Percent</span></div><div class="h-64"><canvas id="cloud-cpu-chart" class="block size-full"></canvas></div></section><section class="chart-panel"><div class="panel-heading"><h2>Network throughput</h2><span>Bytes per interval</span></div><div class="h-64"><canvas id="cloud-network-chart" class="block size-full"></canvas></div></section><section class="chart-panel"><div class="panel-heading"><h2>Disk I/O</h2><span>Bytes per interval</span></div><div class="h-64"><canvas id="cloud-disk-chart" class="block size-full"></canvas></div></section><section class="chart-panel"><div class="panel-heading"><h2>Status checks</h2><span>Failed checks</span></div><div class="h-64"><canvas id="cloud-status-chart" class="block size-full"></canvas></div></section></div>
        </div>
        <section data-cloud-detail-panel="insights" class="chart-panel mt-5 hidden">
            <div class="panel-heading"><h2>Storage</h2><span id="cloud-storage-summary">Filesystem usage and EBS capacity</span></div>
            <div class="flex items-center justify-between gap-3"><h3 class="text-sm font-medium">Mounted filesystems</h3><span id="cloud-filesystem-summary" class="text-xs text-slate-500">CloudWatch Agent</span></div>
            <div id="cloud-filesystem-list" class="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-3"></div>
            <div class="mt-5 border-t border-slate-200 pt-4 dark:border-slate-800">
                <div class="flex items-center justify-between gap-3"><h3 class="text-sm font-medium">EBS attachments</h3><span id="cloud-volume-summary" class="text-xs text-slate-500">0 volumes</span></div>
                <div id="cloud-volume-list" class="mt-2 divide-y divide-slate-200 dark:divide-slate-800"></div>
            </div>
            <p class="mt-4 text-xs text-slate-500">Filesystem usage comes from the operating system; EBS capacity comes from AWS. LVM, RAID, and partitioning can prevent a direct one-to-one mapping.</p>
        </section>
        <section data-cloud-detail-panel="configuration" class="chart-panel mt-5 hidden"><div class="panel-heading"><h2>Instance configuration</h2><span id="cloud-instance-id">—</span></div><dl class="grid gap-4 text-sm sm:grid-cols-2 xl:grid-cols-6"><div><dt class="text-xs text-slate-500">Account</dt><dd id="cloud-account" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">Region</dt><dd id="cloud-region" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">Availability zone</dt><dd id="cloud-zone" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">Instance type</dt><dd id="cloud-type" class="mt-1 font-medium">—</dd></div><div><dt class="text-xs text-slate-500">Private IP</dt><dd id="cloud-private-ip" class="mt-1 font-mono">—</dd></div><div><dt class="text-xs text-slate-500">Platform</dt><dd id="cloud-platform" class="mt-1 font-medium">—</dd></div></dl></section>
    </div><p id="cloud-error" class="mt-4 hidden rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-500"></p>@endif
</div></main></body></html>
