<!doctype html>
<html lang="en" class="scheme-light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Settings · Pulsewatch</title><script>if(localStorage.getItem('pulsewatch-theme')==='dark'){document.documentElement.classList.add('dark')}</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100"><x-app-header active="settings" />
<main id="settings-page" class="mx-auto max-w-screen-2xl px-4 py-6 sm:px-6"><div><p class="text-sm font-medium text-emerald-600">Administration</p><h1 class="text-2xl font-semibold">Settings</h1><p class="mt-1 text-sm text-slate-500">Install monitoring agents and configure application email delivery.</p></div>
@if(session('status'))<div class="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{{ session('status') }}</div>@endif
<nav class="mt-6 flex gap-2 overflow-x-auto border-b border-slate-200 pb-3 dark:border-slate-800" role="tablist" aria-label="Settings sections"><button type="button" role="tab" data-settings-tab="server-agent" class="rounded-lg px-4 py-2 text-sm font-medium shadow-sm">Server Agent</button><button type="button" role="tab" data-settings-tab="browser-agent" class="rounded-lg px-4 py-2 text-sm font-medium shadow-sm">Browser Agent</button><button type="button" role="tab" data-settings-tab="email-delivery" class="rounded-lg px-4 py-2 text-sm font-medium shadow-sm">Email Settings</button></nav>

<section id="server-agent" data-settings-panel="server-agent" role="tabpanel" class="pt-7"><div class="mb-4"><h2 class="text-xl font-semibold">Install Server Agent</h2><p class="mt-1 text-sm text-slate-500">Install the Java agent on a Linux server to collect CPU, RAM, disk, and process telemetry.</p></div>@include('dashboard.install-agent')</section>

<section id="browser-agent" data-settings-panel="browser-agent" role="tabpanel" class="hidden pt-7"><div class="mb-4"><h2 class="text-xl font-semibold">Install Browser Agent</h2><p class="mt-1 text-sm text-slate-500">Add the JavaScript agent to a website to collect page loads, AJAX/HTMX requests, Web Vitals, and frontend errors.</p></div>
<div class="grid gap-5 xl:grid-cols-2"><div class="chart-panel"><div class="panel-heading"><h3>Register website</h3><span>Exact origin validation</span></div><form method="POST" action="{{ route('browser-monitoring.store') }}" class="space-y-4">@csrf<label class="setup-label">Website name<input name="name" value="{{ old('name') }}" required maxlength="255" class="setup-input mt-2" placeholder="Customer portal"></label><label class="setup-label">Website URL<input name="site_url" value="{{ old('site_url') }}" required type="url" class="setup-input mt-2" placeholder="https://app.example.com"></label><button class="rounded-xl bg-emerald-500 px-5 py-3 font-medium text-white">Generate Browser Agent key</button></form></div>
<div class="chart-panel"><div class="panel-heading"><h3>Browser Agent snippets</h3><a href="{{ route('browser-monitoring.index') }}" class="text-xs text-emerald-600">Open Browser Monitoring</a></div><div class="max-h-96 space-y-4 overflow-auto">@forelse($browserProjects as $project)<article class="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div class="flex justify-between gap-3"><div><p class="font-medium">{{ $project->name }}</p><p class="font-mono text-xs text-slate-500">{{ $project->allowed_origin }}</p></div><span class="text-xs {{ $project->is_active ? 'text-emerald-600' : 'text-slate-400' }}">{{ $project->is_active ? 'Active' : 'Disabled' }}</span></div><textarea readonly rows="4" class="setup-input mt-3 font-mono text-xs">&lt;script src="{{ url('/browser-monitor.js') }}" data-key="{{ $project->public_key }}" data-endpoint="{{ url('/api/v1/browser/events') }}" defer&gt;&lt;/script&gt;</textarea></article>@empty<p class="text-sm text-slate-500">Register a website to generate its installation snippet.</p>@endforelse</div></div></div></section>

<section id="email-delivery" class="scroll-mt-20 py-10"><div class="mb-4"><h2 class="text-xl font-semibold">Email Delivery</h2><p class="mt-1 text-sm text-slate-500">SMTP is used for team invitations and future notification emails. The password is encrypted in the database.</p></div><form method="POST" action="{{ route('settings.mail.update') }}" class="chart-panel">@csrf @method('PATCH')<div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label class="setup-label">SMTP host<input name="host" value="{{ old('host',$mailSetting?->host) }}" required class="setup-input mt-2" placeholder="smtp.example.com"></label><label class="setup-label">Port<input name="port" value="{{ old('port',$mailSetting?->port ?? 587) }}" required type="number" min="1" max="65535" class="setup-input mt-2"></label><label class="setup-label">Connection security<select name="scheme" class="setup-input mt-2"><option value="">Automatic TLS</option><option value="smtp" @selected(old('scheme',$mailSetting?->scheme)==='smtp')>SMTP without implicit TLS</option><option value="smtps" @selected(old('scheme',$mailSetting?->scheme)==='smtps')>SMTPS (implicit TLS)</option></select></label><label class="setup-label">Username<input name="username" value="{{ old('username',$mailSetting?->username) }}" class="setup-input mt-2" autocomplete="off"></label><label class="setup-label">Password<input name="password" type="password" class="setup-input mt-2" autocomplete="new-password" placeholder="{{ $mailSetting && filled($mailSetting->getRawOriginal('password')) ? 'Saved — leave blank to keep' : '' }}"></label><label class="setup-label">From email<input name="from_address" value="{{ old('from_address',$mailSetting?->from_address) }}" required type="email" class="setup-input mt-2"></label><label class="setup-label">From name<input name="from_name" value="{{ old('from_name',$mailSetting?->from_name ?? 'Pulsewatch') }}" required class="setup-input mt-2"></label><label class="flex items-center gap-3 self-end rounded-xl border border-slate-200 p-3 dark:border-slate-700"><input type="hidden" name="is_enabled" value="0"><input type="checkbox" name="is_enabled" value="1" @checked(old('is_enabled',$mailSetting?->is_enabled ?? true)) class="size-4">Enable SMTP delivery</label></div><div class="mt-5"><button class="rounded-xl bg-emerald-500 px-5 py-3 font-medium text-white">Save email settings</button></div>@if($errors->any())<div class="mt-4 text-sm text-red-500">{{ $errors->first() }}</div>@endif</form></section>
</main></body></html>
